"""Worked example of the anti-tautology contract check — copy per real source, then delete this.

The rule (see ``src/config/CLAUDE.md`` → "Pin every contract to a source-published oracle"): a
``FileContract`` is only *correct* when checked against something **the source produced**, never
against itself. So the columns are pinned to a **committed header fixture** — the verbatim first
line of the real artifact, generated by ``bin/pin_contract_oracle.py`` (never hand-typed to match
the contract) — and this test asserts ``contract.tuple_required == header_from_fixture``.

Header-only fixtures carry no data rows, so this pattern is safe even when the artifact holds
personal data. Copy ``example_source.py`` + ``example_source__header.csv`` + this test per real
source; delete all three examples once your own contracts exist.
"""

from pathlib import Path

# Bare ``config.`` prefix (not ``src.config.``) — matches the cross-module test convention
# (see test_provenance): a ``src.`` copy of the module has a distinct FileContract identity.
from config.contracts import EXAMPLE_SOURCE


_FIXTURE = Path(__file__).resolve().parent.parent / "fixtures" / "example_source__header.csv"


def _oracle_columns(path_fixture: Path, str_sep: str = ";") -> tuple[str, ...]:
	"""Return the committed header fixture's columns (the source-produced oracle).

	Parameters
	----------
	path_fixture : pathlib.Path
		Path to the header-only fixture (the verbatim first line of the real artifact).
	str_sep : str, optional
		Column delimiter (default ``";"``).

	Returns
	-------
	tuple of str
		The oracle columns, in the source's own order.
	"""
	str_header = path_fixture.read_text(encoding="utf-8").splitlines()[0]
	return tuple(cell.strip() for cell in str_header.split(str_sep))


def test_example_contract_matches_its_source_oracle() -> None:
	"""``EXAMPLE_SOURCE.tuple_required`` equals the committed source header (not itself)."""
	assert set(EXAMPLE_SOURCE.tuple_required) == set(_oracle_columns(_FIXTURE))
