#!/usr/bin/env node
/**
 * Emits a plain-JavaScript copy of this project's `src/` + `public/` into
 * `js-copy/`, for delivery contexts that must not contain TypeScript (a
 * course submission, a client handoff, a consumer with no TS toolchain).
 *
 * Strips types with @babel/core + @babel/preset-typescript — both are
 * already devDependencies (babel-loader uses them on every build), so this
 * adds no new dependency.
 *
 * The generated webpack.config.js bakes in two fixes that only surface
 * *after* the extension change from .ts/.tsx to .js/.jsx, both with error
 * messages that point away from the real cause:
 *   1. A `.babelrc` in the copy is resolved against the invoking shell's
 *      cwd, not the copy's own root, so it is silently ignored when built
 *      from elsewhere. Presets are declared inline instead, with
 *      `babelrc: false, configFile: false`.
 *   2. `"type": "module"` puts every `.js` under ESM's "fully specified"
 *      import resolution, which requires the extension on every relative
 *      import — `.ts`/`.tsx` are exempt, which is why the TypeScript
 *      original never hits this. `resolve.fullySpecified: false` opts out.
 *
 * Run `node scripts/verify-js-copy.mjs` after this to prove the output (and
 * any document generated alongside it) is actually free of the toolchain.
 */
import { transformSync } from '@babel/core';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const OUT_DIR = path.resolve(PROJECT_ROOT, 'js-copy');

const TS_EXTENSIONS = new Set(['.ts', '.tsx']);
const SKIP_DIR_NAMES = new Set(['node_modules', 'dist', 'coverage', 'js-copy', '.git']);
// Internal developer docs (CLAUDE.md, src/capabilities/_layers/*.md) describe
// the TypeScript layer architecture and reference .ts paths throughout — they
// are not part of the runtime app, and shipping them in a plain-JS delivery
// would disclose the excluded toolchain (see verify-js-copy.mjs).
const SKIP_FILE_EXTENSIONS = new Set(['.md']);

function jsExtensionFor(tsExtension) {
  return tsExtension === '.tsx' ? '.jsx' : '.js';
}

function transpileFile(srcPath, destPath) {
  const source = fs.readFileSync(srcPath, 'utf8');
  const { code } = transformSync(source, {
    filename: srcPath,
    babelrc: false,
    configFile: false,
    presets: [
      ['@babel/preset-env', { targets: '> 0.25%, not dead' }],
      ['@babel/preset-react', { runtime: 'automatic' }],
      '@babel/preset-typescript',
    ],
  });
  fs.mkdirSync(path.dirname(destPath), { recursive: true });
  fs.writeFileSync(destPath, code);
}

function copyFileVerbatim(srcPath, destPath) {
  fs.mkdirSync(path.dirname(destPath), { recursive: true });
  fs.copyFileSync(srcPath, destPath);
}

function walkAndTranspile(srcDir, destDir) {
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    if (SKIP_DIR_NAMES.has(entry.name)) continue;
    const srcPath = path.join(srcDir, entry.name);
    if (entry.isDirectory()) {
      walkAndTranspile(srcPath, path.join(destDir, entry.name));
      continue;
    }
    const ext = path.extname(entry.name);
    if (SKIP_FILE_EXTENSIONS.has(ext.toLowerCase())) continue;
    if (TS_EXTENSIONS.has(ext)) {
      const destName = entry.name.slice(0, -ext.length) + jsExtensionFor(ext);
      transpileFile(srcPath, path.join(destDir, destName));
    } else {
      copyFileVerbatim(srcPath, path.join(destDir, entry.name));
    }
  }
}

function writeWebpackConfig() {
  const config = `import HtmlWebpackPlugin from 'html-webpack-plugin';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Generated by emit-js-copy.mjs — do not edit by hand, re-run the script instead.
export default {
  // Anchors every relative path to THIS file's directory, so the build
  // behaves the same regardless of the shell's cwd when it is invoked.
  context: __dirname,
  entry: './src/index.jsx',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.[contenthash].js',
    clean: true,
  },
  resolve: {
    extensions: ['.jsx', '.js'],
    // Mirrors the TypeScript original's webpack alias — sources use
    // '@/...' imports throughout (e.g. '@/routes/MainRouter').
    alias: { '@': path.resolve(__dirname, 'src') },
    // "type": "module" requires an extension on every relative import for
    // .js/.jsx (unlike .ts/.tsx, which are exempt) — this copy's sources
    // use extensionless imports, so the ESM rule is opted out here.
    fullySpecified: false,
  },
  module: {
    rules: [
      {
        test: /\\.jsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            // A .babelrc here would be resolved against the invoking
            // shell's cwd and silently ignored — declare presets inline.
            babelrc: false,
            configFile: false,
            presets: [
              ['@babel/preset-env', { targets: '> 0.25%, not dead' }],
              ['@babel/preset-react', { runtime: 'automatic' }],
            ],
          },
        },
      },
      {
        test: /\\.module\\.css$/,
        use: ['style-loader', { loader: 'css-loader', options: { modules: true } }],
      },
      {
        test: /\\.css$/,
        exclude: /\\.module\\.css$/,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
  plugins: [new HtmlWebpackPlugin({ template: './public/index.html', filename: 'index.html' })],
};
`;
  fs.writeFileSync(path.join(OUT_DIR, 'webpack.config.js'), config);
}

function main() {
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  walkAndTranspile(path.join(PROJECT_ROOT, 'src'), path.join(OUT_DIR, 'src'));
  copyFileVerbatim(
    path.join(PROJECT_ROOT, 'public', 'index.html'),
    path.join(OUT_DIR, 'public', 'index.html'),
  );
  writeWebpackConfig();
  console.log(`js-copy: emitted a plain-JavaScript copy to ${path.relative(PROJECT_ROOT, OUT_DIR)}/`);
}

main();
