// @ts-check
// Manual sidebar: this skeleton's docs/ set is small and stable enough that the
// autogenerated sidebar (which would also need excludes for non-doc files) adds
// more indirection than it saves.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: ['index', 'usage', 'examples', 'faq', 'contributing'],
};

module.exports = sidebars;
