# -------------------
# VSCODE CONFIG
# -------------------
.PHONY: vscode_init export_deps

vscode_init:
	@bash scripts/vscode_keybindings.sh
	@bash scripts/vscode_extensions.sh

export_deps:
	@bash scripts/export_deps.sh
