# Slack-compatible webhook configurations.
# Add as many named entries as needed.
<name_webhook>:
  url:
  id_channel:
  username:
  icon_emoji:
  title: TITLE
  message: >
    ROUTINE: {}
    \n \n \t - Executed at: {}.
    \n \n \t - Operator machine: {}
    \n \n \t - Operator ID: {}
    \n \n \t - Evidence available at: {}
    \n \n \t - Logs available at: {}
    \n \n \t Regards,
  bool_debug_mode: false
